version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/demoapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 30
      runas: root
    - location: scripts/start_server
      timeout: 30
      runas: root