version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing Dependencies..............
      - npm install
  build:
    commands:
      - echo Building.............
      - npm run-script build
      - npm install -g serve
  post_build:
    commands:
      - echo Running post_building.....................
      - echo Deploy app build to S3 bucket...................
      - aws s3 cp --recursive ./build s3://test-lucy-client
#artifacts:
#  files:
#    - "**/*"
#  discard-paths: no
#  base_directory: build




