name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      blue-green:
        description: 'Enter to Switch selector for Blue/ Green Deployment'
        required: true
        default: 'Mona the Octocat'


jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Existing Tag
        uses: matheusraz/check-existing-tag-action@v1
        id: check_tag       
        with:
          tag: v1.0.0-rc2

      - name: Tag Existing Result
        run: echo "${{ steps.check_tag.outputs.tag_exists }}"

  
