name: Manually triggered workflow
on:
  push:
    branches:
      - "master"
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: 'Enter to Switch selector for Blue/ Green Deployment'
#         required: true
#         default: 'v1.0.0'


jobs:
  action_test:
    runs-on: ubuntu-latest
#     env:
#       TAG: ${{ github.event.inputs.tag }}
    steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Get current tag
#         id: get-current-tag
#         uses: zingimmick/github-action-get-current-tag@v1
#       - name: Print tag
#         id: print-tag
#         run: TAG=$(echo ${{steps.get-current-tag.outputs.tag}}) && echo "::set-output-name=TAG::$TAG"  && echo "tag is $TAG"
#       - name: get tag
#         run: echo ${{steps.get-current-tag.outputs.tag}}
        - name: getting and setting api version available
          id: set-api-version
          run: |
            version_blue=$(grep blue /release_version |cut -f 2 -d " ") && version_green=$(grep green /release_version |cut -f 2 -d " ")
            echo $version_blue && echo $version_green

#       - name: Check Existing Tag
#         uses: matheusraz/check-existing-tag-action@v1
#         id: check_tag
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag: ${{ github.event.inputs.tag }}

#       - name: Tag Existing Result
#         run: echo "${{ steps.check_tag.outputs.tag_exists }}" && echo "${{ github.event.inputs.tag }}"
#       - name: describe tag
#         id: tag
#         run: TAG=$(echo $(git describe --tags)) && echo "::set-output-name=TAG::$TAG"  && echo "tag is $TAG"
#       - name: prinnt tag  
#         run: TAG=$(echo ${{steps.tag.outputs.tag}}) && echo $TAG

  
