name: Manually triggered workflow
on:
  push:
    tags:
      - "*"
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: 'Enter to Switch selector for Blue/ Green Deployment'
#         required: true
#         default: 'v1.0.0'


jobs:
  action_test:
    runs-on: ubuntu-latest
#     env:
#       TAG: ${{ github.event.inputs.tag }}
    steps:
#       - name: Checkout
#         uses: actions/checkout@v2
      - name: Get current tag
        id: get-current-tag
        uses: zingimmick/github-action-get-current-tag@v1
      - name: Print tag
        id: print-tag
        run: TAG=$(echo ${{steps.get-current-tag.outputs.tag}}) && echo "::set-output-name=TAG::$TAG"  && echo "tag is $TAG"
      - name: get tag
        run: ehco $TAG && echo ${{steps.print-tag.outputs.TAG}}

#       - name: Check Existing Tag
#         uses: matheusraz/check-existing-tag-action@v1
#         id: check_tag
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag: ${{ github.event.inputs.tag }}

#       - name: Tag Existing Result
#         run: echo "${{ steps.check_tag.outputs.tag_exists }}" && echo "${{ github.event.inputs.tag }}"
#       - name: describe tag
#         id: tag
#         run: TAG=$(echo $(git describe --tags)) && echo "::set-output-name=TAG::$TAG"  && echo "tag is $TAG"
#       - name: prinnt tag  
#         run: TAG=$(echo ${{steps.tag.outputs.tag}}) && echo $TAG

  
