name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      blue-green:
        description: 'Enter to Switch selector for Blue/ Green Deployment'
        required: true
        default: 'Mona the Octocat'


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
     - if: blue == ${{github.event.inputs.blue-green}}
       name: echo
       run: echo "Hello ${{ github.event.inputs.blue-green }}!"
     - if: false == ${{github.event.inputs.blue-green}}      
       run: echo "Hello ${{ github.event.inputs.blue-green }}!"
  
