name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter to Switch selector for Blue/ Green Deployment'
        required: true
        default: 'v1.0.0'


jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Existing Tag
        uses: matheusraz/check-existing-tag-action@v1
        id: check_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{github.event.inputs.tag}}
        with:
          tag: $TAG

      - name: Tag Existing Result
        run: echo "${{ steps.check_tag.outputs.tag_exists }}"

  
