name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      blue-green:
        description: 'Enter to Switch selector for Blue/ Green Deployment'
        required: true
        default: 'Mona the Octocat'


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: getting blue version
        id: main
        run: deploy=${{github.event.inputs.blue-green}} && echo "::set-output name=deploy::$deploy "
        if: steps.main.outputs.deploy == blue
      - name: enter
        run: echo "enter version is blue"
 

  
