# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
 workflow_dispatch:
  inputs:
    operatorcode:
      description: 'Enter Operatorcode'
      required: true
      default: "BUSSR"

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{matrix.OperatorCode == 'PAHALA'}}
    strategy:
      matrix:
        OperatorCode: [BUSSR, PAHALA, ADIBUZZ ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: test operator
      if: ${{matrix.OperatorCode == 'PAHALA'}}
      run: echo ${{matrix.OperatorCode}}
    - name: Return message
      if: ${{matrix.OperatorCode == 'BUSSR'}}
      run: echo ${{matrix.OperatorCode}}
    - name: operator code
      if: ${{matrix.OperatorCode == 'ADIBUZZ'}}
      run: echo ${{matrix.OperatorCode}}
