# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
 workflow_dispatch:
  inputs:
    operatorcode:
      description: 'Enter Operatorcode'
      required: true
      default: "BUSSR"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        OperatorCode: [BUSSR, PAHALA, ADIBUZZ ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: APP build
      if: ${{matrix.OperatorCode == 'PAHALA'}}
      run: echo "OperatorCode is PAHALA"
    - name: Return message
      if: ${{matrix.OperatorCode == 'BUSSR'}}
      run: echo "OperatorCode is BUSSR"
    - name: operator code
      if: ${{matrix.OperatorCode == 'ADIBUZZ'}}
      run: echo"OperatorCode is ADIBUZZ"
